add not found message

diff --git a/.script/grep b/.script/grep
--- a/.script/grep
+++ b/.script/grep
@@ -13,6 +13,11 @@ keyword="$@"
 
 hashes=`cat ${workdir}/.paperdb | grep -iE "$keyword" | cut -f1`
 
+if [ -z "$hashes" ]; then
+  printf "[-] Not found\n"
+  exit 1
+fi
+
 printf "[+] %d paper(s) found.\n" "`echo \"$hashes\" | wc -l`"
 
 for x in $hashes; do
